### ISSUE TITLE
VirtualBox on MacOS complains on default proposed network configuration

### ISSUE THREAD

**Issue by mathieubodin-sfeir** [axinorm/kubeadm-automation#2]
After executing `vagrant up`, I got the following message:

```
==> k8s-master: Clearing any previously set network interfaces...
The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.

  Address: 10.0.0.10
  Ranges: 192.168.56.0/21

Valid ranges can be modified in the /etc/vbox/networks.conf file. For
more information including valid format see:

  https://www.virtualbox.org/manual/ch06.html#network_hostonly
```

Then the configuration `group_vars/kube-cluster.yml` become wrong:

```yaml
---
master_ip: 10.0.0.10
...
```

After fixing `Vagrantfile` and `group_vars/kube-cluster.yml` accordingly, everything's fine.

## My two cents:

Out of the box, the installation process through `vagrant up` can't work due to virtual box limitations on network configuration. It  
may be documented somewhere (this issue might be a start 😋).

How `master_ip` is determined should be fixed to avoid over configuration.

## My stack:

```sh
uname -a
# Darwin frde01l406.happly.fr 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

VBoxManage --version
# 6.1.32r149290

vagrant --version
# Vagrant 2.2.19

python3 --version
# Python 3.9.10

pip3 --version
# pip 22.0.3

ansible --version
# ansible [core 2.12.2]
#   config file = None
#   python version = 3.9.10
#   jinja version = 3.0.3
#   libyaml = True
```

**Comment by axinorm** [comment]
I merged your Pull Request and add content in the README file in case of virtualbox network limitations.

Thanks !
